etags -a attrib.c   
etags -a attrib.h   
etags -a debug.h    
etags -a defaults.h 
etags -a dfa.c      
etags -a dfa.h      
etags -a dtdparser.c
etags -a intset.c   
etags -a intset.h   
etags -a mem.c      
etags -a mem.h      
etags -a saxhandler.c
etags -a saxhandler.h
etags -a saxparser.c
etags -a saxparser.h
etags -a setset.c   
etags -a setset.h   
etags -a stack.c    
etags -a stack.h    
etags -a strtree.c  
etags -a strtree.h  
etags -a symtab.c   
etags -a symtab.h   
etags -a xml.lex.c  
etags -a xml.tab.c  
etags -a xml.tab.h  
